# Generated by Django 2.0.9 on 2018-11-29 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64)),
                ('resource', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('amount', models.IntegerField(default=0)),
                ('pai_amount', models.IntegerField(default=0)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lon', models.FloatField(blank=True, default=25.01735)),
                ('lat', models.FloatField(blank=True, default=121.539794)),
                ('provider', models.CharField(default='Anonymous provider', max_length=20)),
            ],
        ),
    ]
