# Generated by Django 2.0.9 on 2018-12-06 17:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64)),
                ('resource', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('amount', models.IntegerField(default=0)),
                ('pai_amount', models.IntegerField(default=0)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lon', models.FloatField(blank=True, default=25.01735)),
                ('lat', models.FloatField(blank=True, default=121.539794)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lon', models.FloatField(blank=True, default=25.01735)),
                ('lat', models.FloatField(blank=True, default=121.539794)),
            ],
        ),
        migrations.CreateModel(
            name='TakeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rating', models.IntegerField(default=0)),
                ('food', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodevent.FoodEvent')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
