# Generated by Django 2.0.9 on 2018-12-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodevent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lon', models.FloatField(blank=True, default=25.01735)),
                ('lat', models.FloatField(blank=True, default=121.539794)),
            ],
        ),
    ]
