# Generated by Django 2.1.1 on 2018-11-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodevent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodevent',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
