# Generated by Django 2.0.9 on 2018-12-06 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodevent',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
