# Generated by Django 2.0.9 on 2018-12-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodevent', '0002_auto_20181228_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place',
            new_name='name',
        ),
    ]
