# Generated by Django 2.0.9 on 2018-11-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodevent', '0003_rental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
