# Generated by Django 2.0.9 on 2018-11-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodevent', '0006_foodevent_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodevent',
            name='pai_amount',
            field=models.IntegerField(default=0),
        ),
    ]
